export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR';

export const FETCH_COMPANIES_REQUEST = 'FETCH_COMPANIES_REQUEST';
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_ERROR = 'FETCH_COMPANIES_ERROR';

export const FETCH_LOC_COMMON_REQUEST = 'FETCH_LOC_COMMON_REQUEST';
export const FETCH_LOC_COMMON_SUCCESS = 'FETCH_LOC_COMMON_SUCCESS';
export const FETCH_LOC_COMMON_ERROR = 'FETCH_LOC_COMMON_ERROR';

export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR';

export const FETCH_CTRL_SET_NUMBER = 'FETCH_CTRL_SET_NUMBER';
export const FETCH_CTRL_INCREMENT = 'FETCH_CTRL_INCREMENT';

export const SET_SELECTABLES_LOADED = 'SET_SELECTABLES_LOADED';